### ISSUE TITLE
저장된 데이터를 가지고 Notification

### ISSUE THREAD

**Issue by gon-park** [29-75/web-crawling#4]
- 저장된 데이터를 가지고 Notification
  1. Notification 정책을 수립한다.
      - 보관된/업데이트 된 데이터를 통해 언제 어떤 데이터를 Noti. 할 것 인가?
  1. Kakao chat bot을 등록한다.
  1. Kakao chat bot engine(server)를 만들고 동작을 검증한다.
  1. Kakao chat bot을 이용하여 channel에 notification을 한다.
      - Merge 전에 Dummy 데이터를 넣어서 동작을 검증

**Comment by sungwon-ahn** [comment]
지지고볶자

**Comment by mbj0528** [comment]
챗봇 https://github.com/bzantium/chatbot-seminar
카카오 플러스 친구 (채널) 만들고 OBT 참여해서 kakao i developer OBT 등록 해서 챗봇 이용하는 것 같음.

**Comment by sungwon-ahn** [comment]
- 2020 04 22 개발일지
    - Kakao chat bot을 등록한다.

**Comment by mbj0528** [comment]
- 2020 04 29 개발일지
  - Kakao Open Builder 승인 재신청.
  - 플라스크 서버 동작 방식
    - 엔진에서 주기적으로 서버 호출하면 채널로 전송
      - current, previous Data 로 Rank(Rank up, down, New ...) Status 추출 필요
    - 사용자 요청에 대한 응답
      - 해당 정보를 Channel에 Return

**Comment by sungwon-ahn** [comment]
Service Flow 

- 1. List all update

    - 크롤링엔진에서 주기적인 리스트 업데이트 처리.
    - 이후, 카카오 채널쪽으로 push 하여 사용자로 하여금 받게 한다.

- 2. List GET 특정 카테고리 관련 기사 list
    - 사용자가 지정한 키워드에 따른 관련기사 조회
    - 사용자가 채팅으로 키워드를 지정 (#시사,#IT) 이를 통한 필터링후 전달

- 3. List GET top3,
    - 현재 기사 들의 Ranking 을 기반으로 top 3 의 기사들만 전달

- 4. List GET top5,
    - 현재 기사 들의 Ranking 을 기반으로 top 5 의 기사들만 전달

**Comment by sungwon-ahn** [comment]
- 2020 05 06 개발일지
  - KaKao ChatBot Service
    - update_news, list_all, top3, top5  서비스 추가
    - update_news 는 크롤링 엔진에서 update 발생시 호출하는 서비스 (http://localhost:8080/update_news)

  - KaKao open builder 
    - aws vm 생성,

**Comment by mbj0528** [comment]
2020 05 27 마치며...
- 패치노트
    - card list 는 5개가 최대여서 outputs에 array형식으로 출력하게끔 변경
    - 링크가 안눌리는 문제 수정 : link type 은 mourl -> mobile, pcurl -> pc, weburl -> web 으로 수정
- 메모
    - skill 등록시 시나리오 발화와 연동 필요
- 기능
    - 발화 -> 스킬 호출
        - 뉴스 -> list_all 호출
        - 뉴스3 -> top3 호출
        - 뉴스5 -> top5 호출
        - 뉴스10 -> top10 호출
- 기타
    - aws ubuntu에 docker로 동작.
